// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIFaJbVn9bRJpcqnncLHJ1LG6CT800f4',
    appId: '1:312534534473:web:7a03f0502154f7fab27298',
    messagingSenderId: '312534534473',
    projectId: 'chat-app-ddc69',
    authDomain: 'chat-app-ddc69.firebaseapp.com',
    storageBucket: 'chat-app-ddc69.appspot.com',
    measurementId: 'G-JX5VT34DSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnofb3UijiHiBra9NJk7S9IxN6hzd5PI',
    appId: '1:312534534473:android:c40efcb233528130b27298',
    messagingSenderId: '312534534473',
    projectId: 'chat-app-ddc69',
    storageBucket: 'chat-app-ddc69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiNdmHeFb1Dvvx8wSynXpOwpfOr_7gRnA',
    appId: '1:312534534473:ios:c2270f545f3436ebb27298',
    messagingSenderId: '312534534473',
    projectId: 'chat-app-ddc69',
    storageBucket: 'chat-app-ddc69.appspot.com',
    iosBundleId: 'com.moace.chatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiNdmHeFb1Dvvx8wSynXpOwpfOr_7gRnA',
    appId: '1:312534534473:ios:bcb7f2b97bbfa0e8b27298',
    messagingSenderId: '312534534473',
    projectId: 'chat-app-ddc69',
    storageBucket: 'chat-app-ddc69.appspot.com',
    iosBundleId: 'com.moace.chatApp.chatApp.RunnerTests',
  );
}
